import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Food Crafts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-gray-600 font-caveat">
        
        <div className="grid md:grid-cols-3">
          <Navbar/>
          {children}
        </div>
        </body>
    </html>
  )
}
